## Data Encoding
1. Nominal/OHE Encoding
2. Label and Orginal Encoding
3. Taarget Guided Orginal Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.DataFrame({'Color': ['red', 'green', 'blue', 'green', 'red']})
df

   Color
0    red
1  green
2   blue
3  green
4    red

In [3]:
# we create a instance of the OneHotEncoder
encoder = OneHotEncoder()

In [7]:
## perform fit and transform
encoder.fit_transform(df[['Color']]).toarray()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
encoded = encoder.fit_transform(df[['Color']]).toarray()

In [ ]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   Color_blue  Color_green  Color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0

In [12]:
encoder.transform([['blue']]).toarray()

c:\Users\rashi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [13]:
pd.concat([df, encoder_df], axis=1)

   Color  Color_blue  Color_green  Color_red
0    red         0.0          0.0        1.0
1  green         0.0          1.0        0.0
2   blue         1.0          0.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0

In [14]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## Lebel Encoding

In [15]:
df.head()

   Color
0    red
1  green
2   blue
3  green
4    red

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [18]:
le.fit_transform(df[['Color']])

c:\Users\rashi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 0, 1, 2])

In [22]:
le.transform(['red'])

array([2])

In [25]:
##ordinal encoding

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

In [28]:
df = pd.DataFrame({'size': ['small', 'medium', 'large', 'medium', 'small']})

In [29]:
df

     size
0   small
1  medium
2   large
3  medium
4   small

In [31]:
## create a instance of the OrdinalEncoder than fit and transform
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [ ]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.]])

In [34]:
encoder.transform([['small']])

c:\Users\rashi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

## Target Guided Ordinal Encoding

In [37]:
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney', 'New York', 'Paris'],
    'price': [100, 200, 150, 300, 250, 100, 150]
})

In [38]:
df

       city  price
0  New York    100
1    London    200
2     Paris    150
3     Tokyo    300
4    Sydney    250
5  New York    100
6     Paris    150

In [40]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [41]:
mean_price

{'London': 200.0,
 'New York': 100.0,
 'Paris': 150.0,
 'Sydney': 250.0,
 'Tokyo': 300.0}

In [44]:
df['city_encoded'] = df['city'].map(mean_price)

In [48]:
df[['price', 'city_encoded']]

   price  city_encoded
0    100         100.0
1    200         200.0
2    150         150.0
3    300         300.0
4    250         250.0
5    100         100.0
6    150         150.0

In [49]:
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]